### ISSUE TITLE
Uncaught TypeError: this.grammar.onDidUpdate is not a function

### ISSUE THREAD

**Issue by Ulrik-dk** [atom/styleguide#74]
[Enter steps to reproduce:]

1. Open Atom.

**Atom**: 1.37.0 x64
**Electron**: 4.1.4
**OS**: "Manjaro Linux"
**Thrown From**: [styleguide](https://github.com/atom/styleguide) package 0.49.12

### Stack Trace

Uncaught TypeError: this.grammar.onDidUpdate is not a function

```
At /usr/lib/atom/src/text-mate-language-mode.js:36

TypeError: this.grammar.onDidUpdate is not a function
    at new TextMateLanguageMode (/usr/lib/atom/src/text-mate-language-mode.js:36:39)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/usr/lib/atom/src/grammar-registry.js:174:14)
    at GrammarRegistry.assignLanguageMode (/usr/lib/atom/src/grammar-registry.js:139:35)
    at new CodeBlock (/usr/lib/atom/node_modules/styleguide/lib/code-block.js:9:19)
    at render (/usr/lib/atom/node_modules/etch/lib/render.js:17:25)
    at addChildren (/usr/lib/atom/node_modules/etch/lib/render.js:39:24)
    at render (/usr/lib/atom/node_modules/etch/lib/render.js:29:21)
    at addChildren (/usr/lib/atom/node_modules/etch/lib/render.js:39:24)
    at render (/usr/lib/atom/node_modules/etch/lib/render.js:29:21)
    at updateChildren (/usr/lib/atom/node_modules/about/node_modules/etch/lib/patch.js:109:34)
    at patch (/usr/lib/atom/node_modules/about/node_modules/etch/lib/patch.js:15:9)
    at updateSync (/usr/lib/atom/node_modules/about/node_modules/etch/lib/component-helpers.js:108:20)
    at /usr/lib/atom/node_modules/about/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/usr/lib/atom/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.32 
highlight-selected 0.16.0 
intentions 1.1.5 
language-assembly 0.7.2 
language-fsharp 0.8.4 
linter 2.3.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
```

**Comment by rsese** [comment]
Thanks for the report!

> **Atom**: 1.37.0 x64
> **Electron**: 4.1.4

Based on these versions, we've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
